title: Kevin Penate's Portfolio
description: A showcase of my work, writing, and projects.
remote_theme: "mmistakes/minimal-mistakes"
url: "https://ronniekev.github.io"
baseurl: "/github-Portfolio"

author:
  name: Kevin Penate
  avatar: "/assets/images/avatar.jpg"
  bio: Full-stack developer passionate about building meaningful software.
  links:
    - label: "GitHub"
      url: "https://github.com/ronniekev"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/kevin-penate-52a39215b/"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
  navigation:
  - title: "Home"
    url: "/github-Portfolio/"
  - title: "Projects"
    url: "/github-Portfolio/projects/"
  - title: "About"
    url: "/github-Portfolio/about/"

